name: Unit Tests

on:
  push:
    branches:
      - TestCase
  pull_request:
    branches: [TestCase]

jobs:
  Jest:
    name: Run Test Case
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test